import { mkdir, writeFile } from 'node:fs/promises';
const out=new URL('../fixtures/',import.meta.url);await mkdir(out,{recursive:true});
const rt=s=>({type:'rich_text',rich_text:[{plain_text:s,text:{content:s}}]}), tt=s=>({type:'title',title:[{plain_text:s,text:{content:s}}]}), se=s=>({type:'select',select:s?{name:s}:null}), ms=a=>({type:'multi_select',multi_select:a.map(name=>({name}))}), re=a=>({type:'relation',relation:a.map(id=>({id}))}), da=s=>({type:'date',date:s?{start:s}:null}), nu=n=>({type:'number',number:n}), cb=b=>({type:'checkbox',checkbox:b}), ph=s=>({type:'phone_number',phone_number:s}), ur=s=>({type:'url',url:s}), fi=(name,url)=>({type:'files',files:[{name,type:'external',external:{url}}]});
const page=(source,n,properties)=>({id:`${source.toLowerCase()}-${n}`,url:`https://example.invalid/${source}/${n}`,created_time:'2026-01-01T00:00:00.000Z',last_edited_time:'2026-01-02T00:00:00.000Z',archived:false,in_trash:false,properties});
const data={
CLASS:[page('CLASS',1,{'반이름':tt('중등 A'),'담당교사':rt('가상강사'),'요일별담당교사':rt('월=1:가상강사'),'요일':ms(['월']),'시간':rt('16:00'),'레벨':se('중등'),'구분':se('정규'),'소속학생':re(['student-1']),'담당조교':re(['staff-2'])}),page('CLASS',2,{'반이름':tt('고등 B'),'담당교사':rt('가상강사'),'요일별담당교사':rt('잘못된 형식'),'요일':ms(['화']),'시간':rt('18:00'),'레벨':se('고등'),'구분':se('정규'),'소속학생':re(['student-2']),'담당조교':re([])})],
STUDENT:[page('STUDENT',1,{'이름':tt('가상학생1'),'학교':rt('가상중'),'학년':se('중2'),'상태':se('재원'),'연락처':ph('000-0000-0000'),'학부모연락처':ph('000-0000-0001'),'소속반':re(['class-1']),'누적출석률':{type:'rollup',rollup:{type:'number',number:.9}},'누적숙제제출률':{type:'rollup',rollup:{type:'number',number:.8}},'누적단어테스트통과율':{type:'rollup',rollup:{type:'number',number:.7}},'등록일':da('2026-01-01'),'등원일':da('2026-01-02'),'회비일':nu(10),'학습레벨':rt('B1'),'레벨Lv':nu(2),'메모':rt('가상'),'조치':rt(''),'조치담당자':rt(''),'조치알람일':da(null)}),page('STUDENT',2,{'이름':tt('가상학생2'),'학교':rt('가상고'),'학년':se('고1'),'상태':se('재원'),'연락처':ph(null),'학부모연락처':ph(null),'소속반':re(['class-2']),'등록일':da('2026-01-01'),'등원일':da('2026-01-02'),'회비일':nu(20),'학습레벨':rt('C1'),'레벨Lv':nu(4),'메모':rt(''),'조치':rt(''),'조치담당자':rt(''),'조치알람일':da(null)})],
CLASS_PROGRESS:[page('CLASS_PROGRESS',1,{'제목':tt('진도1'),'반':re(['class-1']),'날짜':da('2026-01-03'),'수업과목':ms(['문법']),'진도내용':rt('1과'),'과제내용':rt('문제'),'다음시간테스트':rt('단어'),'전달사항':rt('없음'),'교시':se('1교시'),'학생기록생성됨':cb(true),'생성된학생기록':re(['daily_record-1'])}),page('CLASS_PROGRESS',2,{'제목':tt('진도2'),'반':re(['class-2']),'날짜':da('2026-01-04'),'수업과목':ms([]),'진도내용':rt(''),'과제내용':rt(''),'다음시간테스트':rt(''),'전달사항':rt(''),'교시':se(null),'학생기록생성됨':cb(true),'생성된학생기록':re(['daily_record-2'])})],
DAILY_RECORD:[page('DAILY_RECORD',1,{'제목':tt('일일1'),'학생':re(['student-1']),'반':re(['class-1']),'날짜':da('2026-01-03'),'진도내용':rt('1과'),'출결':se('출석'),'과제여부':cb(true),'단어테스트결과':se('통과'),'반별진도원본':re(['class_progress-1']),'비고':rt(''),'성취사항':rt('[]')}),page('DAILY_RECORD',2,{'제목':tt('일일2'),'학생':re(['student-2']),'반':re(['class-2']),'날짜':da('2026-01-04'),'진도내용':rt('2과'),'출결':se('지각'),'과제여부':cb(false),'단어테스트결과':se('재시험'),'반별진도원본':re(['class_progress-2']),'비고':rt('가상'),'성취사항':rt('[]')})],
BRIEFING:[page('BRIEFING',1,{'제목':tt('브리핑1'),'학생':re(['student-1']),'날짜':da('2026-01-03'),'브리핑유형':se('전달사항'),'브리핑내용':rt('가상 내용')}),page('BRIEFING',2,{'제목':tt('브리핑2'),'학생':re(['student-2']),'날짜':da('2026-01-04'),'브리핑유형':se('주의'),'브리핑내용':rt('가상 내용')})],
EXAM_SCORE:[page('EXAM_SCORE',1,{'제목':tt('성적1'),'학생':re(['student-1']),'시험명':rt('중간'),'과목':se('영어'),'점수':nu(90),'날짜':da('2026-04-01')}),page('EXAM_SCORE',2,{'제목':tt('성적2'),'학생':re(['student-2']),'시험명':rt('기말'),'과목':se('영어'),'점수':nu(85),'날짜':da('2026-07-01')})],
COUNSELING:[page('COUNSELING',1,{'제목':tt('상담1'),'학생':re(['student-1']),'날짜':da('2026-01-03'),'상담자':rt('가상강사'),'전사내용':rt('가상'),'상담내용':rt('가상'),'후속조치':rt('없음'),'입력자':rt('가상')}),page('COUNSELING',2,{'제목':tt('상담2'),'학생':re(['student-2']),'날짜':da('2026-01-04'),'상담자':rt('가상강사'),'전사내용':rt(''),'상담내용':rt('가상'),'후속조치':rt(''),'입력자':rt('가상')})],
ADMIN_INBOX:[page('ADMIN_INBOX',1,{'제목':tt('문의1'),'입력유형':se('결석예정'),'대상학생':re(['student-1']),'날짜':da('2026-01-03'),'종료일':da('2026-01-04'),'내용':rt('가상'),'처리완료':cb(false),'입력자':rt('가상'),'담당자':rt('가상')}),page('ADMIN_INBOX',2,{'제목':tt('문의2'),'입력유형':se('문의'),'대상학생':re(['student-2']),'날짜':da('2026-01-04'),'종료일':da(null),'내용':rt('가상'),'처리완료':cb(true),'입력자':rt('가상'),'담당자':rt('가상')})],
TODO:[page('TODO',1,{'제목':tt('할일1'),'유형':se('클리닉'),'담당자':re(['staff-2']),'관련학생':re(['student-1']),'관련반':re(['class-1']),'예정일':da('2026-01-03'),'시간':rt('17:00'),'메모':rt('가상'),'완료여부':cb(false),'우선순위':se('보통'),'클리닉보고':re(['clinic-1']),'결석수업내용':rt('')}),page('TODO',2,{'제목':tt('할일2'),'유형':se('보강'),'담당자':re(['staff-1']),'관련학생':re(['student-2']),'관련반':re(['class-2']),'예정일':da('2026-01-04'),'시간':rt(''),'메모':rt('가상'),'완료여부':cb(false),'우선순위':se('높음'),'클리닉보고':re([]),'결석수업내용':rt('2과')})],
STAFF:[page('STAFF',1,{'이름':tt('가상강사'),'역할':se('강사'),'PIN':rt('REDACTED_FIXTURE'),'비번변경필요':cb(false),'근무시간표':rt('월=14:00-18:00'),'근무요일':ms(['월'])}),page('STAFF',2,{'이름':tt('가상조교'),'역할':se('조교'),'PIN':rt('REDACTED_FIXTURE'),'비번변경필요':cb(true),'근무시간표':rt('파싱실패'),'근무요일':ms(['화'])})],
CLINIC:[page('CLINIC',1,{'제목':tt('클리닉1'),'조교':re(['staff-2']),'담당학생':re(['student-1']),'담당강사':re(['staff-1']),'관련업무':re(['todo-1']),'날짜':da('2026-01-03'),'진행내용':rt('가상'),'다음준비사항':rt('가상'),'확인완료':cb(false)}),page('CLINIC',2,{'제목':tt('클리닉2'),'조교':re(['staff-missing']),'담당학생':re(['student-2']),'담당강사':re(['staff-1']),'관련업무':re([]),'날짜':da('2026-01-04'),'진행내용':rt('가상'),'다음준비사항':rt(''),'확인완료':cb(true)})],
MATERIAL:[page('MATERIAL',1,{'제목':tt('자료1'),'요청자':re(['staff-1']),'담당자':re(['staff-2']),'작업내용':rt('가상 제작'),'작업률':nu(30),'상태':se('작업중'),'마감일':da('2026-02-01'),'파일저장위치':ur('https://example.invalid/files/1'),'원본파일':fi('sample.pdf','https://example.invalid/sample.pdf')}),page('MATERIAL',2,{'제목':tt('자료2'),'요청자':re(['staff-1']),'담당자':re([]),'작업내용':rt('가상 제작'),'작업률':nu(0),'상태':se('요청됨'),'마감일':da('2026-02-02'),'파일저장위치':ur(null),'원본파일':{type:'files',files:[]}})],
EXAM_PREP:[page('EXAM_PREP',1,{'제목':tt('대비1'),'학생':re(['student-1']),'시험명':rt('중간'),'담당교사':rt('가상강사'),'진행률':nu(0),'취약부분':rt('어법'),'갱신일':da('2026-01-03'),'학교급':se('중등'),'데이터':rt(JSON.stringify({level:'중등',middle:{textSources:[],schoolPrint:'',practiceItems:{'자주 틀리는 문제':[],'기출문제':[],'백발백중':[],'적중백':[],'추가문제':[]}}}))}),page('EXAM_PREP',2,{'제목':tt('대비2'),'학생':re(['student-2']),'시험명':rt('기말'),'담당교사':rt('가상강사'),'진행률':nu(0),'취약부분':rt(''),'갱신일':da('2026-01-04'),'학교급':se('고등'),'데이터':rt('{invalid-json')})],
SCHOOL_EXAM_RANGE:[page('SCHOOL_EXAM_RANGE',1,{'제목':tt('범위1'),'학교':rt('가상중'),'학년':se('중2'),'시험명':rt('중간'),'시험범위':rt('1-2과'),'시험시작일':da('2026-04-01'),'시험종료일':da('2026-04-02'),'교과서명':rt('교과서'),'교과서단원':rt('1과,2과'),'부교재명':rt('부교재'),'부교재단원':rt('1단원'),'모의고사명':rt(''),'모의고사단원':rt(''),'학교프린트명':rt(''),'학교프린트단원':rt(''),'갱신일':da('2026-01-03')}),page('SCHOOL_EXAM_RANGE',2,{'제목':tt('범위2'),'학교':rt('가상고'),'학년':se('고1'),'시험명':rt('기말'),'시험범위':rt('전범위'),'시험시작일':da('2026-07-01'),'시험종료일':da('2026-07-02'),'교과서명':rt('교과서'),'교과서단원':rt('3과'),'부교재명':rt('부교재'),'부교재단원':rt('2단원'),'모의고사명':rt('2606'),'모의고사단원':rt('18-20'),'학교프린트명':rt('프린트'),'학교프린트단원':rt('A'),'갱신일':da('2026-01-04')})],
SLACK_RECORDS:[page('SLACK_RECORDS',1,{'제목':tt('슬랙1'),'학생':re(['student-1']),'작성시각':da('2026-01-03T01:00:00Z'),'원문':rt('가상 메시지'),'Slack작성자':rt('가상작성자'),'원문링크':ur('https://example.invalid/slack/1'),'상태':se('완료'),'연결상태':se('연결됨')}),page('SLACK_RECORDS',2,{'제목':tt('슬랙2'),'학생':re(['student-2']),'작성시각':da('2026-01-04T01:00:00Z'),'원문':rt('가상 메시지'),'Slack작성자':rt('가상작성자'),'원문링크':ur('https://example.invalid/slack/2'),'상태':se('대기'),'연결상태':se('연결됨')})]};
for(const[source,rows]of Object.entries(data))await writeFile(new URL(`${source}.json`,out),JSON.stringify(rows,null,2)+'\n');
